const fs = require('fs');

let root = fs.readFileSync('app/layout.tsx', 'utf8');
root = root.replace('export const metadata: Metadata = {', '/* export const metadata: Metadata = {');
root = root.replace('description: \"Generated by create next app\",\n};', 'description: \"Generated by create next app\",\n}; */\n\nimport { getSEOSettings, getWebsiteSettings } from \"@/lib/services/cms/cms.service\";\n\nexport async function generateMetadata(): Promise<Metadata> {\n  const [seo, website] = await Promise.all([\n    getSEOSettings(\"global\"),\n    getWebsiteSettings()\n  ]);\n\n  return {\n    title: seo?.title || website?.siteName || \"Sky Crackers\",\n    description: seo?.description || \"Premium Quality Fireworks\",\n    keywords: seo?.keywords,\n    openGraph: seo?.ogImage ? { images: [seo.ogImage] } : undefined,\n    icons: website?.faviconUrl ? { icon: website.faviconUrl } : undefined,\n  };\n}');
fs.writeFileSync('app/layout.tsx', root);
