import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

import { getSEOSettings, getWebsiteSettings } from "@/lib/services/cms/cms.service";

export async function generateMetadata(): Promise<Metadata> {
  const [seo, website] = await Promise.all([
    getSEOSettings("global"),
    getWebsiteSettings()
  ]);

  return {
    title: seo?.title || website?.siteName || "Sky Crackers",
    description: seo?.description || "Premium Quality Fireworks",
    keywords: seo?.keywords,
    openGraph: seo?.ogImage ? { images: [seo.ogImage] } : undefined,
    
  };
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-white text-gray-900" suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
